services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d:ro
      - ./certbot/www/:/var/www/certbot:ro
      - ./certbot/conf/:/etc/letsencrypt:ro
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/conf:/etc/letsencrypt:rw
      - ./certbot/www:/var/www/certbot:rw
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build: ../backend
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/mydb
      HOSTNAME: cleverengineer.games
    depends_on:
      - db

  frontend:
    build: ../frontend
    environment:
      HOSTNAME: cleverengineer.games
      MODE: production
    depends_on:
      - backend

  adminer:
    image: adminer
    depends_on:
      - db

volumes:
  postgres-data:
