services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d:ro
      - ./certbot/www/:/var/www/certbot:ro
      - ./certbot/conf/:/etc/letsencrypt:ro
    restart: always

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/conf:/etc/letsencrypt:rw
      - ./certbot/www:/var/www/certbot:rw
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    restart: always

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

  backend:
    build: ../backend
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/mydb
      HOSTNAME: cleverengineer.games
      GOOGLE_CLIENT_ID: /run/secrets/google_client_id
      GOOGLE_CLIENT_SECRET: /run/secrets/google_client_secret
      GITHUB_CLIENT_ID: /run/secrets/github_client_id
      GITHUB_CLIENT_SECRET: /run/secrets/github_client_secret
    secrets:
      - google_client_id
      - google_client_secret
      - github_client_id
      - github_client_secret
    depends_on:
      - db
    restart: always

  frontend:
    build: ../frontend
    environment:
      HOSTNAME: cleverengineer.games
      MODE: production
    depends_on:
      - backend
    restart: always

  adminer:
    image: adminer
    depends_on:
      - db
    restart: always

volumes:
  postgres-data:

secrets:
  google_client_id:
    file: ./secrets/google_client_id.txt
  google_client_secret:
    file: ./secrets/google_client_secret.txt
  github_client_id:
    file: ./secrets/github_client_id.txt
  github_client_secret:
    file: ./secrets/github_client_secret.txt
